use shipyard::{NonSendSync, UniqueView, Unique, AllStoragesView};
use glium::{texture::{SrgbTexture2dArray, MipmapsOption}, Program};
use kubi_shared::block::{Block, BlockTexture};
use crate::rendering::Renderer;

mod texture;
mod shaders;

use texture::load_texture2darray_prefab;
use shaders::include_shader_prefab;

pub trait AssetPaths {
  fn file_name(self) -> &'static str;
}

impl AssetPaths for BlockTexture {
  fn file_name(self) -> &'static str {
    match self {
      Self::Stone         => "stone.png",
      Self::Dirt          => "dirt.png",
      Self::GrassTop      => "grass_top.png",
      Self::GrassSide     => "grass_side.png",
      Self::Sand          => "sand.png",
      Self::Bedrock       => "bedrock.png",
      Self::Wood          => "wood.png",
      Self::WoodTop       => "wood_top.png",
      Self::Leaf          => "leaf.png",
      Self::Torch         => "torch.png",
      Self::TallGrass     => "tall_grass.png",
      Self::Snow          => "snow.png",
      Self::GrassSideSnow => "grass_side_snow.png",
      Self::Cobblestone   => "cobblestone.png",
      Self::Planks        => "planks.png",
      Self::WaterSolid    => "solid_water.png",
    }
  }
}

#[derive(Unique)]
pub struct BlockTexturesPrefab(pub SrgbTexture2dArray);

#[derive(Unique)]
pub struct ChunkShaderPrefab(pub Program);

#[derive(Unique)]
pub struct SelBoxShaderPrefab(pub Program);

#[derive(Unique)]
pub struct ColoredShaderPrefab(pub Program);

#[derive(Unique)]
pub struct ProgressbarShaderPrefab(pub Program);

pub fn load_prefabs(
  storages: AllStoragesView,
  renderer: NonSendSync<UniqueView<Renderer>>
) {
  log::info!("Loading textures...");
  storages.add_unique_non_send_sync(BlockTexturesPrefab(
    load_texture2darray_prefab::<BlockTexture, _>(
      "./assets/blocks/".into(), 
      &renderer.display,
      MipmapsOption::AutoGeneratedMipmaps
    )
  ));

  log::info!("Compiling shaders...");
  storages.add_unique_non_send_sync(ChunkShaderPrefab(
    include_shader_prefab!(
      "world",
      "../shaders/world.vert",
      "../shaders/world.frag",
      &renderer.display
    )
  ));
  storages.add_unique_non_send_sync(SelBoxShaderPrefab(
    include_shader_prefab!(
      "selection_box",
      "../shaders/selection_box.vert",
      "../shaders/selection_box.frag",
      &renderer.display
    )
  ));
  storages.add_unique_non_send_sync(ColoredShaderPrefab(
    include_shader_prefab!(
      "colored",
      "../shaders/colored.vert",
      "../shaders/colored.frag",
      &renderer.display
    )
  ));
  storages.add_unique_non_send_sync(ProgressbarShaderPrefab(
    include_shader_prefab!(
      "gui/progressbar",
      "../shaders/gui/progressbar.vert",
      "../shaders/gui/progressbar.frag",
      &renderer.display
    )
  ));
}
