use shipyard::{NonSendSync, UniqueView, Unique, AllStoragesView};
use glium::{texture::{SrgbTexture2dArray, MipmapsOption}, Program};
use strum::EnumIter;
use crate::rendering::Renderer;

mod texture;
mod shaders;

use texture::load_texture2darray_prefab;
use shaders::include_shader_prefab;

pub trait AssetPaths {
  fn file_name(self) -> &'static str;
}

#[derive(Clone, Copy, Debug, EnumIter)]
#[repr(u8)]
pub enum BlockTexture {
  Stone         = 0,
  Dirt          = 1,
  GrassTop      = 2,
  GrassSide     = 3,
  Sand          = 4,
  Bedrock       = 5,
  Wood          = 6,
  WoodTop       = 7,
  Leaf          = 8,
  Torch         = 9,
  TallGrass     = 10,
  Snow          = 11,
  GrassSideSnow = 12,
}
impl AssetPaths for BlockTexture {
  fn file_name(self) -> &'static str {
    match self {
      Self::Stone         => "stone.png",
      Self::Dirt          => "dirt.png",
      Self::GrassTop      => "grass_top.png",
      Self::GrassSide     => "grass_side.png",
      Self::Sand          => "sand.png",
      Self::Bedrock       => "bedrock.png",
      Self::Wood          => "wood.png",
      Self::WoodTop       => "wood_top.png",
      Self::Leaf          => "leaf.png",
      Self::Torch         => "torch.png",
      Self::TallGrass     => "tall_grass.png",
      Self::Snow          => "snow.png",
      Self::GrassSideSnow => "grass_side_snow.png",
    }
  }
}

#[derive(Unique)]
pub struct BlockTexturesPrefab(pub SrgbTexture2dArray);

#[derive(Unique)]
pub struct ChunkShaderPrefab(pub Program);

pub fn load_prefabs(
  storages: AllStoragesView,
  renderer: NonSendSync<UniqueView<Renderer>>
) {
  storages.add_unique_non_send_sync(BlockTexturesPrefab(
    load_texture2darray_prefab::<BlockTexture, _>(
      "./assets/blocks/".into(), 
      &renderer.display,
      MipmapsOption::AutoGeneratedMipmaps
    )
  ));
  storages.add_unique_non_send_sync(ChunkShaderPrefab(
    include_shader_prefab!(
      "../shaders/world.vert",
      "../shaders/world.frag",
      &renderer.display
    )
  ));
}
